### ISSUE TITLE
Update Validations class to utilize `read_attribute` instead of magic getters

### ISSUE THREAD

**Issue by brianmuse** [robinpowered/php-activerecord#3]
The `Validations` class, which often performs pre-flight DB validations (eg. uniqueness), utilizes magic getter methods.

However, if the magic getters are overridden by the child class to provide additional abstraction or serialization, this causes an issue where you wouldn't get expected results from running validations. For example the raw attribute may be `4`, which would succeed with `validates_numericality_of`, however the magic getter may abstract this value to an `Enum` class or another value, causing the validation to fail.

Instead of using magic getters, the raw values in the `attributes` array should be used. However since this property is private and since attributes may be aliased by the library, it will be best to replace instances of magic getters in the `Validations` class with `read_attribute` calls.

**Comment by Rican7** [comment]
Fixed in #5?
